words=['förmåga','kan','om','ovan','acceptera','enligt','konto','över','address','administration',
'erkänna','vuxen', 'påverka', 'efter', 'igen', 'mot', 'ålder', 'byrå',
'agent','agreement','före','luft','alla','tillåta','nästan','ensam',
'med','redan','även','även om','alltid','amerikansk','bland','belopp',
'analys','och','djur','annat','svar','alla','något','visas',
'area','argumentera','arm','runt','konst','artikel',
'konstnär','som','fråga','anta','på','attack','uppmärksamhet','advokat','publik',
'författare','auktoritet','tillgänglig','undvika','borta',
'bank','bar','bas','be','beat','vacker','säng','före',
'börja', 'beteende', 'bakom', 'tro', 'nytta', 'bäst', 'bättre', 'mellan',
'bortom','bok', 'född', 'båda', 'låda', 'pojke', 'bryta', 'bringa', 'bror', 'budget', 'bygga',
'bygga','företag','men','köpa','genom','ringa','kamera','kampanj','kan','cancer',
'kandidat', 'kapital', 'bil', 'kort', 'vård', 'karriär', 'bära', 'ärende', 'fånga',
'orsak','cell','center','central','talet','visst','visst','stol',
'utmana','chans','change','character','charge','check','child','choice',
'välj', 'kyrka', 'medborgare', 'stad', 'medborgerlig', 'anspråka', 'klass', 'tydlig', 'tydligt',
'nära','coach','kall', 'kollektion', 'färg', 'kom', 'kommersiell'
,'företag','jämföra','computer','kondition',
'kostnad', 'kan', 'land', 'par', 'kurs', 'domstol', 'täcka', 'skapa', 'brott',
'kulturell','kultur','kopp','nuvarande','kund','klippa',
'mörkt','data','data','dotter','dag','död','deal','debatt','decennium','besluta',
'beslut', 'djup', 'försvar', 'grad', 'demokrat', 'demokratisk', 'beskriva', 'design',
'trots', 'detalj', 'bestämma', 'utveckla', 'utveckling', 'dö', 'skillnad',
'annorlunda', 'svårt', 'middag', 'riktning', 'regissör', 'upptäcka', 'diskutera',
'diskussion', 'sjukdom', 'göra', 'läkare', 'hund', 'dörr', 'nedåt', 'rita', 'drömma', 'köra',
'släpp', 'drog', 'under',
'varje', 'tidig', 'öst', 'lätt', 'äta', 'ekonomisk', 'ekonomi', 'kant', 'utbildning',
'effekt', 'ansträngning', 'åtta', 'antingen', 'val', 'annat', 'anställd', 'slut', 'energi',
'njut','nog','enter','hela','miljö','miljömässiga','speciellt',
'etablera', 'jämn', 'kväll', 'event', 'någonsin', 'alla', 'alla', 'alla',
"allt", "bevis", "exakt", "exempel", "verkställande", "existerar", "förväntar sig",
'erfarenhet', 'expert', 'förklara', 'öga',
'ansikte', 'fakta', 'faktor', 'misslyckande', 'fall', 'familj', 'långt', 'snabb', 'far', 'rädsla',
'federal','få','film','final',
'äntligen','finansiell','hitta','fin','finger','finish',
'fisk', 'fem', 'golv', 'fluga', 'fokusera', 'följa', 'mat', 'fot', 'för', 'kraft',
'utländsk', 'glömma', 'form', 'tidigare', 'framåt', 'fyra', 'gratis', 'vän',
'från','framifrån','fullständig','fond','framtid',
'spel', 'trädgård', 'gas', 'allmänt', 'generation', 'get', 'tjej', 'ge', 'glas', 'gå',
'mål', 'bra', 'regering', 'bra', 'grön', 'mark', 'grupp', 'växa', 'tillväxt',
'gissa', 'pistol', 'kille',
'hår', 'halv', 'hand', 'hänga', 'hända', 'glad', 'svårt', 'har', 'han', 'huvud', 'hälsa',
'hör', 'hjärta', 'värme', 'tung', 'hjälp', 'henne', 'här', 'själv', 'hög', 'honom',
'själv', 'hans', 'historia', 'hit', 'håll', 'hem', 'hopp', 'sjukhus', 'het', 'hotell',
'timme', 'hus', 'hur', 'men', 'stor', 'människa', 'hundra', 'make',
'idé', 'identifiera', 'om', 'bild', 'föreställ dig', 'påverkan', 'viktigt', 'förbättra',
'inkludera', 'inklusive', 'öka', 'verkligen', 'indikera', 'individuell', 'industri',
'information','inuti','istället','intresse','intressant',
'internationell','intervju','investering','involvera','problematik',
'det','objekt','det','själv','jobb','gå med','bara','behåll','nyckel','barn','döda','snäll',
'kök','veta','kunskap','land','språk','stora','senaste','sena','senare',
'skratta', 'lag', 'advokat', 'lägga', 'leda', 'ledare', 'lära', 'minst', 'lämna', 'vänster','sannolikt',
'linje','lista','lyssna','liten','live','lokal','lång','titta','förlora','förlust',
'mycket', 'kärlek',
'maskin', 'tidning', 'huvud', 'underhåll', 'stor', 'majoritet', 'make', 'man',
'ledning', 'manager', 'många', 'marknad', 'äktenskap', 'material', 'materia', 'kan',
'kanske','jag','mäta','media',
'minne', 'omnämnande', 'meddelande', 'metod', 'mitten', 'kan', 'militär', 'miljoner',
'minne','minut','missa','modell','pengar','månad',
'mer', 'morgon', 'mest', 'mamma', 'mun', 'rörelse', 'rörelse', 'film', 'mycket', 'musik',
'måste','namn',
'nation', 'nationell', 'naturlig', 'natur', 'nära', 'nästan', 'nödvändig', 'behov',
'nätverk','aldrig','ny','nyheter','tidning','nästa','trevlig','natt','nej','ingen',
'notera','ingenting','nu','nummer',
'förekommer','av','erbjudande','kontor','officiell','ofta',
'olja', 'gammal', 'på', 'en gång', 'en', 'bara', 'på', 'öppen', 'drift', 'möjlighet',
'alternativ','eller','order','organisation','annan','vår','ute','utanför','över',
'egen','ägare','sida','smärta','Målning','papper','förälder',
'del','deltagare','speciell','speciellt','partner','party',
'pass','kanske', 'period', 'person', 'personlig', 'telefon', 'politisk',
'politik', 'fattig', 'populär', 'befolkning', 'position', 'positiv', 'möjlig',
'kraft', 'ganska', 'race', 'radio',
'höja','räckvidd','snarare','räcka','läs','redo','verklig','verklighet','inse',
'verkligen','nyss',
'reducera','reflektera','region','relatera','relation',
'komma ihåg','ta bort','rapportera','representera','republikan',
'resurs', 'svara', 'svar', 'ansvar', 'kör', 'säker', 'samma', 'spara',
'säg', 'scen', 'skola', 'vetenskap', 'vetenskapsman', 'poäng', 'hav', 'säsong', 'säte','sekund','skicka','senior',
'serie', 'service',
'ställ','sju','flera','skaka','dela','hon','skjuta','kort','shot','bör',
'axel','visa','sida','tecken','liknande','enkel','helt enkelt','eftersom',
'sjunga','single','syster','sitt','site','situation',
'så', 'socialt', 'samhälle', 'soldat', 'någon', 'någon', 'någon', 'något',
'ibland', 'tal', 'spendera', 'sport', 'vår', 'personal', 'scen', 'stå', 'standard',
'stjärna','start','station','stilla','steg','still','orginal',
'stopp', 'butik', 'berättelse', 'strategi', 'gata', 'stark', 'struktur', 'student', 'studie',
'grejer','stil','ämne','framgång','framgångsrika','sådana','plötsligt','lider',
'föreslå','sommar','support','system','ta','tala',
'uppgift','skatt','lära','lärare','teknik','television','berätta','tio',
'test','än','tack','sak','tänk','tredje','detta','de',
'fast', 'tänkte', 'tusen', 'hot', 'tre', 'genom', 'genom', 'kasta',
'således', 'tid', 'till', 'idag', 'tillsammans', 'ikväll', 'även', 'totalt', 'tufft',
'mot', 'stad', 'handel', 'traditionell', 'träning', 'resa', 'behandla', 'behandling',
'träd','försök','resa','problem','sant','sanning','försök','sväng','TV','två','typ',
'under','förstå','enhet','tills','upp','på','oss','använd','vanligtvis','värde',
'olika', 'mycket', 'offer', 'se', 'våld', 'besök', 'röst', 'rösta', 'vänta',
'vapen', 'slitage', 'vecka', 'vikt', 'jo', 'väst', 'västern', 'vad', 'vad som helst',
'när','var','om','varför','vid','fru','kommer','vinn','vind',
'fönster','önske','med','inom','utan','kvinna','undrar','ord','arbete',
'arbetare', 'värld', 'oro', 'skulle', 'skriva', 'författare', 'fel', 'gård',
'ja', 'år', 'ja', 'ännu', 'du', 'ung', 'dig', 'själv']
